#!/bin/bash
#
#
# chkconfig: 345 70 30
# description: Filebeat send log to Elasticsearch
# processname: filebeat-log
### BEGIN INIT INFO
# Provides:
# Required-Start:
# Required-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
### END INIT INFO
#
#
#  Filebeat Log API
#  /etc/init.d/filebeat-api
#
#
# Source function library.
. /etc/init.d/functions
PROGNAME=filebeat-god
PROG=/usr/share/filebeat/bin/$PROGNAME
USER=root
LOGFILE=/var/log/$PROGNAME.log
LOCKFILE=/var/run/$PROGNAME.pid
start() {
    echo -n "Starting $PROGNAME: "
    daemon --user $USER --pidfile="$LOCKFILE" "$PROG -r / -n -p /var/run/filebeat.pid -- /usr/share/filebeat/bin/filebeat -path.config /opt/filebeat-es -path.data /opt/filebeat-es -path.logs /opt/filebeat-es &>$LOGFILE &"
    echo $(pidofproc $PROGNAME) >$LOCKFILE
    echo
}
stop() {
    echo -n "Shutting down $PROGNAME: "
    killproc $PROGNAME
    rm -f $LOCKFILE
    echo
}
case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    status)
    status $PROGNAME
    ;;
    restart)
    stop
    start
    ;;
    reload)
    echo "Sending SIGHUP to $PROGNAME"
    kill -SIGHUP $(pidofproc $PROGNAME)#!/bin/bash
    ;;
    *)
        echo "Usage: service statsd_exporter {start|stop|status|reload|restart}"
        exit 1
    ;;
esac