#!/bin/bash
#
# Nginx-exporter Export statistics to be consumed by a remote Prometheus server
#
# chkconfig: 345 70 30
# description: Prometheus nginx exporter
# processname: nginx-prometheus-exporter
### BEGIN INIT INFO
# Provides:
# Required-Start:
# Required-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
### END INIT INFO
#
#
#  Prometheus nginx exporter
#  /etc/init.d/nginx-exporter
#
#
# Source function library.
. /etc/init.d/functions
PROGNAME=nginx-prometheus-exporter
PROG=/usr/sbin/$PROGNAME
USER=root
LOGFILE=/var/log/PROGNAME=$PROGNAME.log
LOCKFILE=/var/run/$PROGNAME.pid
start() {
    echo -n "Starting $PROGNAME: "
    daemon --user $USER --pidfile="$LOCKFILE" "$PROG -nginx.scrape-uri http://localhost/status &>$LOGFILE &"
    echo $(pidofproc $PROGNAME) >$LOCKFILE
    echo
}
stop() {
    echo -n "Shutting down $PROGNAME: "
    killproc $PROGNAME
    rm -f $LOCKFILE
    echo
}
case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    status)
    status $PROGNAME
    ;;
    restart)
    stop
    start
    ;;
    reload)
    echo "Sending SIGHUP to $PROGNAME"
    kill -SIGHUP $(pidofproc $PROGNAME)#!/bin/bash
    ;;
    *)
        echo "Usage: service nginx-exporter {start|stop|status|reload|restart}"
        exit 1
    ;;
esac